# Generated by Django 2.0.1 on 2024-09-16 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0025_auto_20240512_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='contact_photos/default_photo.png', upload_to='contact_photos/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 14, 7, 6, 265424)),
        ),
    ]
