# Generated by Django 2.0.1 on 2024-11-20 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0029_auto_20240917_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.PositiveIntegerField(default=5, help_text='Время в секундах между сменой слайдов.')),
                ('auto', models.BooleanField(default=True, help_text='Автоматическое переключение слайдов.')),
                ('loop', models.BooleanField(default=True, help_text='Переключение слайдов по кругу.')),
                ('navs', models.BooleanField(default=True, help_text='Вывод стрелочек для навигации.')),
                ('pags', models.BooleanField(default=True, help_text='Вывод пагинации.')),
                ('stopMouseHover', models.BooleanField(default=True, help_text='Остановка автопереключения при наведении мыши.')),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 14, 33, 22, 820908)),
        ),
    ]
