# Generated by Django 2.0.1 on 2024-11-21 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0032_auto_20241121_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_description',
            field=models.TextField(default='staff'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 13, 20, 11, 296549)),
        ),
    ]
